services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    command: npm run dev
    networks:
      - demo-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - demo-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml
    networks:
      - demo-net 

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./app:/demo-app
      - ./loki/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - demo-net 

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - demo-net

  k6:
    image: grafana/k6:latest
    volumes:
      - ./load:/scripts
    entrypoint: ["k6", "run", "/scripts/load.js"]
    environment:
      - K6_LOG_LEVEL=error
    networks:
      - demo-net
    depends_on:
      - app

networks:
  demo-net:
    driver: bridge
